register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: POST

# rutas a la API bajo JWT Auth
api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path:     /login_check
    methods:  [POST]